import { useMemo, useState } from "react";
import { Link, useSearchParams } from "react-router-dom";

const ALLOWED_HOST = "storage.googleapis.com";
const ALLOWED_PATH_PREFIX = "/ksl-omni-uploads/quotations/";

function getValidPdfUrl(rawUrl) {
  if (!rawUrl) return "";

  try {
    const url = new URL(rawUrl);
    const pathname = url.pathname.toLowerCase();

    if (url.protocol !== "https:") return "";
    if (url.hostname !== ALLOWED_HOST) return "";
    if (!url.pathname.startsWith(ALLOWED_PATH_PREFIX)) return "";
    if (!pathname.endsWith(".pdf")) return "";

    return url.href;
  } catch {
    return "";
  }
}

function getFilename(pdfUrl) {
  try {
    const url = new URL(pdfUrl);
    return decodeURIComponent(url.pathname.split("/").pop() || "quotation.pdf");
  } catch {
    return "quotation.pdf";
  }
}

function getStoredQuotation(searchParams) {
  const quote = searchParams.get("quote") || searchParams.get("id") || "";
  const token = searchParams.get("token") || "";
  if (!quote || !token) return null;

  const params = new URLSearchParams({ quote, token });
  return {
    quote,
    token,
    pdfUrl: `/api/quotation?${params.toString()}`,
    filename: `${quote.replace(/[^a-zA-Z0-9_-]/g, "_") || "quotation"}.pdf`,
  };
}

export default function QuotationViewer() {
  const [searchParams] = useSearchParams();
  const [copied, setCopied] = useState(false);
  const storedQuotation = useMemo(() => getStoredQuotation(searchParams), [searchParams]);
  const legacyPdfUrl = useMemo(() => getValidPdfUrl(searchParams.get("file") || searchParams.get("pdf")), [searchParams]);
  const pdfUrl = storedQuotation?.pdfUrl || legacyPdfUrl;
  const filename = storedQuotation?.filename || getFilename(legacyPdfUrl);
  const title = storedQuotation?.quote || filename;
  const shareUrl = typeof window !== "undefined" ? window.location.href : "";

  async function shareQuotation() {
    setCopied(false);

    if (navigator.share) {
      try {
        await navigator.share({
          title: "Official Quotation",
          text: "View your official quotation PDF.",
          url: shareUrl,
        });
        return;
      } catch (error) {
        if (error?.name === "AbortError") return;
      }
    }

    try {
      await navigator.clipboard.writeText(shareUrl);
      setCopied(true);
      window.setTimeout(() => setCopied(false), 2200);
    } catch {
      setCopied(false);
    }
  }

  return (
    <main className="quotation-viewer">
      <header className="quotation-viewer__header">
        <Link className="quotation-viewer__brand" to="/omni" aria-label="Back to KS Omni">
          <img src="/ksl-logo-circle.webp" alt="" width="44" height="44" />
          <span>
            <strong>K.S. Leow Group</strong>
            <small>Quotation Viewer</small>
          </span>
        </Link>

        {pdfUrl && (
          <div className="quotation-viewer__actions" aria-label="Quotation actions">
            <a className="quotation-viewer__button quotation-viewer__button--secondary" href={pdfUrl} target="_blank" rel="noreferrer">
              Open PDF
            </a>
            <a className="quotation-viewer__button" href={pdfUrl} download={filename}>
              Download
            </a>
            <button className="quotation-viewer__button quotation-viewer__button--secondary" type="button" onClick={shareQuotation}>
              {copied ? "Link Copied" : "Share"}
            </button>
          </div>
        )}
      </header>

      <section className="quotation-viewer__body">
        {pdfUrl ? (
          <>
            <div className="quotation-viewer__meta">
              <div>
                <p>Official Quotation</p>
                <h1>{title}</h1>
              </div>
              <span>PDF</span>
            </div>

            <div className="quotation-viewer__frame">
              <iframe title="Official quotation PDF" src={pdfUrl} />
            </div>
          </>
        ) : (
          <div className="quotation-viewer__empty">
            <img src="/ksl-logo-circle.webp" alt="" width="56" height="56" />
            <h1>Quotation Link Unavailable</h1>
            <p>
              This viewer needs a valid quotation PDF link generated by KS Omni. Please request a new quotation from the assistant.
            </p>
            <Link className="quotation-viewer__button" to="/omni">
              Back to KS Omni
            </Link>
          </div>
        )}
      </section>
    </main>
  );
}
